name: "General Workflow, import to all the repositories"
on:  
  workflow_call:
    inputs:
      deploy-env:
        description: Entorno sobre el que desplegar (DEV o PRO)
        required: true
        default: DEV
        type: choice
        options:
          - DEV
          - PRO
      
jobs:  
  build:    
    runs-on: ubuntu-latest
    environment: ${{ inputs.deploy-env || 'DEV' }}
    
    steps:
      - name: Checkout código        
        uses: actions/checkout@v4

      - name: Install Hakcaton CLi        
        uses: ./.github/actions/hackatoncli

      - name: Install Hakcaton CLi        
        uses: ./.github/actions/configurenetwork

      - name: Static code analisis        
        uses: ./.github/actions/sonnarqube_analisis

      - name: Build App
        run: |
          echo "Construyendo aplicación..."
          /*
          * 
          * 
          Ramdom but usefull code
          *
          *
          */
          
      
      - name: Unit tests
        run: |
          echo "Testeando aplicación..."
          /*
          * 
          * 
          Ramdom but usefull code
          *
          *
          */
          

      - name: Upload Artifact
        need: Build App && Test App && Deploy App Dev == success
        run: |
          /*
          * 
          * 
          Ramdom but usefull code
          *
          *
          */
          
      - name: Deploy
        run: |
            if [ "${{ inputs.deploy-env }}" = "PRO" ]; then
              echo "Desplegando en PRODUCCIÓN, esperando autorización del equipo de DevOps"
            else
              echo "Desplegando en ${{ inputs.deploy-env || 'DEV' }}"
            fi
  
